* Jek.el

Jek.el is a static website generator written in emacs lisp. As the
name of the project suggests, the functionality of jek.el is inspired
by the famous static website generator Jekyll which is written in
Ruby.

** Features

- simple configuration via `defjekel` macro
- basic blogging features
  - permalinks
  - optional integration of disqus as commenting engine
- layout support via markup.el
- predefined publishing functions for
  - less css
  - sass/scss css
  - coffeescript
  - markup.el documents

** TODO Usage

Yet to come...

* License
Copyright (c) 2012 Arthur Leonard Andersen

Author: Arthur Leonard Andersen <leoc.git@gmail.com>
URL: http://github.com/leoc/jek.el
Version: 1.0.0
Keywords: Convenience, Markup, HTML

This file is not part of GNU Emacs.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 3
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Emacs; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
Boston, MA 02110-1301, USA.
