* Jek.el

Jek.el is an extension to the org-mode publishing.

** Upcoming Features

- simple configuration via org-publish
- basic blog features
  - tags (tag clouds)
  - categories
  - permalinks
  - integration of disqus as commenting engine
- enhanced layout support via markup.el
- predefined publishing functions for
  - less css
  - coffeescript
  - markup.el documents

** Usage

*** jekel/create-project

This will create a dummy project with the least amount of files
necessary to run jekel.

*** jekel/create-page

This will create a new page. Emacs will ask for the file name of the
new page.

*** jekel/create-post

This will create a new post inside the `_posts` directory. Emacs will
ask for a title of the new post and create a new post with the current
date.

*** jekel/publish

When the current buffer shows an org file, then it will go up the
directory structure and look for a `config.el` file, which contains
the jek.el project configuration.

When it´s found, it gets loaded and the project will be published.
Otherwise you will be asked for a project to publish. It is actually a
wrapper for org-modes `org-publish-project`.

* License
Copyright (c) 2012 Arthur Leonard Andersen

Author: Arthur Leonard Andersen <leoc.git@gmail.com>
URL: http://github.com/leoc/jek.el
Version: 1.0.0
Keywords: Convenience, Markup, HTML

This file is not part of GNU Emacs.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 3
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Emacs; see the file COPYING.  If not, write to the
Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
Boston, MA 02110-1301, USA.
